### ISSUE TITLE
Error with vagrant setup

### ISSUE THREAD

**Issue by akashlevy** [PrincetonUniversity/COS461-Spring2016#1]
When I follow the instructions for assignment 0 and then perform `vagrant up`, I get the result:

> Bringing machine 'default' up with 'virtualbox' provider...
> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> vm:
> - The box 'ubuntu/trusty64' could not be found.
> 
> shell provisioner:
> - The following settings shouldn't exist: run

**Comment by minmit** [comment]
What version of vagrant are you using?

**Comment by akashlevy** [comment]
1.4.3

I installed it using Ubuntu software center... should I not have done that?

**Comment by akashlevy** [comment]
Virtualbox version is 4.3.36 and is 32-bit

**Comment by akashlevy** [comment]
Problem solved! I think I was using a bad version of either Vagrant or Virtualbox from the software center. I downloaded the .deb files from the vendor sites and installed them and then it worked. :)

**Comment by ronaldo-ferreira** [comment]
Great!
